"""Typed configuration + YAML loader for the Audiobook Generation system.

Single source of truth for the text-normalization corpus, the trainable TN
model, the TTS backends, audio post-processing, document parsing, agent
thresholds and serving. Paths come from environment variables so nothing is
hard-coded (required by the assignment).

Environment overrides
---------------------
* ``AUDIOBOOK_AI_ARTIFACTS_DIR`` – base for data/models/runs (Drive on Colab)
* ``AUDIOBOOK_AI_DATA_DIR``      – datasets / generated corpus cache
* ``AUDIOBOOK_AI_MODEL_DIR``     – trained models
* ``AUDIOBOOK_AI_RUN_DIR``       – eval/benchmark/analysis JSON
* ``AUDIOBOOK_AI_OUTPUT_DIR``    – generated audiobooks (wav/mp3/m4b/srt)
* ``HF_HOME``                    – HuggingFace cache
* ``AUDIOBOOK_AI_LLM_API_KEY``   – optional key for the LLM-reasoning fallback brain
"""

from __future__ import annotations

import os
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml


def _env(key: str, default: Optional[str] = None) -> Optional[str]:
    v = os.environ.get(key)
    return v if v not in (None, "") else default


def artifacts_dir() -> Path:
    return Path(_env("AUDIOBOOK_AI_ARTIFACTS_DIR", "artifacts")).expanduser()


def data_dir() -> Path:
    return Path(_env("AUDIOBOOK_AI_DATA_DIR", str(artifacts_dir() / "data"))).expanduser()


def model_dir() -> Path:
    return Path(_env("AUDIOBOOK_AI_MODEL_DIR", str(artifacts_dir() / "models"))).expanduser()


def run_dir() -> Path:
    return Path(_env("AUDIOBOOK_AI_RUN_DIR", str(artifacts_dir() / "runs"))).expanduser()


def output_dir() -> Path:
    return Path(_env("AUDIOBOOK_AI_OUTPUT_DIR", str(artifacts_dir() / "outputs"))).expanduser()


# The 16 semiotic classes our normalizer handles (Sproat & Jaitly, 2016 taxonomy,
# trimmed to the classes that matter for English audiobooks).
SEMIOTIC_CLASSES: List[str] = [
    "PLAIN", "PUNCT", "CARDINAL", "ORDINAL", "DECIMAL", "DIGIT", "MONEY",
    "MEASURE", "DATE", "TIME", "FRACTION", "TELEPHONE", "ELECTRONIC",
    "ABBREV", "ROMAN", "VERBATIM",
]


# ─────────────────────────────────────────────────────────────────────────────
# Sub-configs
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class DataConfig:
    """Text-normalization training corpus (see docs/data_description.md).

    Primary source is a reproducible, context-rich SYNTHETIC corpus generated by
    ``data/tn_corpus.py`` (every semiotic class, with injected ambiguity such as
    "St." -> Saint vs Street). An optional real HF dataset can be mixed in.
    """
    # Optional real (written, spoken) TN dataset id; "" => pure synthetic.
    hf_tn_dataset: str = ""
    hf_tn_config: str = ""
    hf_tn_text_col: str = "before"
    hf_tn_target_col: str = "after"
    # Small VERIFIED English unit-test set for an independent sanity slice (optional).
    eval_sanity_dataset: str = "DigitalUmuganda/Text_Normalization_Challenge_Unittests_Eng_Fra"
    # Optional natural carrier sentences (semiotic tokens are injected into them);
    # falls back to built-in templates when the corpus cannot be downloaded.
    carrier_corpus: str = "Salesforce/wikitext"
    carrier_config: str = "wikitext-2-raw-v1"
    use_carrier_corpus: bool = False        # off by default => fully offline
    # Synthetic corpus sizes.
    synthetic_train_size: int = 60000
    synthetic_val_size: int = 4000
    synthetic_test_size: int = 4000
    hard_slice_size: int = 1500             # ambiguous / context-dependent eval slice
    max_chars: int = 360                    # drop overly long generated examples
    seed: int = 42


@dataclass
class ModelConfig:
    """Trainable Text-Normalization seq2seq model + base / fallback."""
    # ByT5 is char-level => robust to OOV tokens, typos and odd number formats
    # (the dominant failure mode of word-piece T5 on TN). t5-small is the small-GPU
    # fallback (the notebook auto-switches on T4).
    base_model: str = "google/byt5-small"
    base_model_fallback: str = "google-t5/t5-small"
    task_prefix: str = "normalize: "
    max_source_length: int = 384
    max_target_length: int = 384
    # training (HF Seq2SeqTrainer)
    num_train_epochs: int = 3
    learning_rate: float = 5.0e-4           # ByT5 fine-tunes best at a higher LR (t5-small: ~3e-4)
    per_device_train_batch_size: int = 32
    per_device_eval_batch_size: int = 64
    gradient_accumulation_steps: int = 8    # effective batch 256 on H100 (profile holds it constant)
    warmup_ratio: float = 0.05
    weight_decay: float = 0.01
    label_smoothing_factor: float = 0.1     # mild regularizer; helps generalization on rare classes
    max_grad_norm: float = 1.0
    dropout_rate: float = 0.1
    early_stopping_patience: int = 4
    eval_steps: int = 500
    save_steps: int = 500
    logging_steps: int = 50
    generation_num_beams: int = 1
    bf16: bool = True
    fp16: bool = False
    tf32: bool = True
    gradient_checkpointing: bool = False
    group_by_length: bool = True
    seed: int = 42
    output_subdir: str = "tn_normalizer"

    @property
    def output_dir(self) -> Path:
        return model_dir() / self.output_subdir


@dataclass
class TtsConfig:
    """Neural TTS backend selection + voice routing.

    SpeechT5 is the default: HF-native, MIT, light enough for a CPU demo, and
    multi-speaker via x-vector embeddings. Kokoro / Parler are higher-quality
    optional backends; ``pyttsx3`` is the offline last-resort with no model.
    """
    backend: str = "auto"                   # "auto"|"speecht5"|"kokoro"|"parler"|"pyttsx3"
    speecht5_model: str = "microsoft/speecht5_tts"
    speecht5_vocoder: str = "microsoft/speecht5_hifigan"
    speecht5_processor: str = "microsoft/speecht5_tts"
    speaker_xvectors: str = "Matthijs/cmu-arctic-xvectors"   # MIT, 7931 x-vectors
    kokoro_model: str = "hexgrad/Kokoro-82M"                 # Apache-2.0
    kokoro_voice: str = "af_heart"
    parler_model: str = "parler-tts/parler-tts-mini-v1"      # Apache-2.0
    parler_description: str = "A clear, calm narrator reads at a measured pace with high quality audio."
    sample_rate: int = 16000                # SpeechT5 native sample rate
    max_chars_per_chunk: int = 480          # SpeechT5 degrades on long inputs => chunk first
    # named voices -> cmu-arctic x-vector indices (US female narrator by default)
    voice_indices: Dict[str, int] = field(default_factory=lambda: {
        "narrator": 7306,   # slt  – US female (the classic tutorial voice)
        "dialogue": 1284,   # bdl  – US male
        "heading": 5022,    # clb  – US female
        "alt_male": 6799,   # rms  – US male
    })
    narrator_voice: str = "narrator"
    dialogue_voice: str = "dialogue"
    heading_voice: str = "heading"


@dataclass
class AudioConfig:
    """Audio post-processing & export."""
    output_formats: List[str] = field(default_factory=lambda: ["wav", "mp3"])
    make_m4b: bool = True                   # chaptered audiobook (needs ffmpeg)
    sentence_gap_ms: int = 250
    paragraph_gap_ms: int = 600
    chapter_gap_ms: int = 1200
    target_lufs: float = -18.0              # ACX/Audible audiobook integrated loudness (-16 = podcast)
    peak_dbfs: float = -3.0                  # ACX true-peak ceiling
    subtitles: bool = True
    subtitle_format: str = "srt"            # "srt" | "vtt"


@dataclass
class ParseConfig:
    """Document parsing, chaptering & segmentation."""
    max_chars_per_segment: int = 480
    min_chars_per_segment: int = 40         # merge tiny fragments into neighbours
    segmenter: str = "auto"                 # "auto"|"pysbd"|"nltk"|"regex"
    # optional NER model for dialogue speaker attribution (MIT); empty => quote-rules only
    ner_model: str = "dslim/bert-base-NER"
    use_ner: bool = False                   # off by default => fully offline / no model download
    chapter_regex: str = r"^\s*(chapter|part|book|section|prologue|epilogue)\b"
    drop_patterns: List[str] = field(default_factory=lambda: [
        r"^\s*page\s+\d+\s*$",
        r"^\s*\d+\s*$",
        r"^\s*table of contents\s*$",
        r"^\s*copyright\b",
    ])
    pdf_min_line_chars: int = 2


@dataclass
class AgentConfig:
    """Agent thresholds (decision points) + optional LLM reasoning brain."""
    # D2 — normalization confidence: below => flag / escalate the segment.
    norm_confidence_min: float = 0.55
    flag_on_baseline_disagreement: bool = True   # neural vs rule disagreement => review signal
    # D3 — audio QA gates (trigger a re-synthesis).
    audio_min_dur_ratio: float = 0.35       # synth duration / expected (chars * 0.06s)
    audio_max_dur_ratio: float = 3.0
    audio_max_silence_ratio: float = 0.65   # fraction of frames below silence floor
    audio_silence_dbfs: float = -45.0
    audio_clip_peak_dbfs: float = -0.1      # near 0 dBFS => clipping
    max_resynth_attempts: int = 2
    # optional cloud brain (off by default; the agent runs fully on rules)
    llm_fallback_enabled: bool = False
    llm_model: str = "claude-haiku-4-5-20251001"
    llm_api_key_env: str = "AUDIOBOOK_AI_LLM_API_KEY"


@dataclass
class ServingConfig:
    model_version: str = "v1"
    api_title: str = "Audiobook Generation API"
    api_version: str = "1.0.0"
    log_jobs: bool = True
    job_log_subdir: str = "job_logs"
    max_chars: int = 400000                 # ~ a short book per request
    max_file_mb: int = 25

    @property
    def job_log_path(self) -> Path:
        return run_dir() / self.job_log_subdir / "jobs.jsonl"


@dataclass
class AppConfig:
    project_title: str = "Audiobook Generation System"
    author: str = "Le Dinh Minh Quan"
    student_id: str = "23127460"
    data: DataConfig = field(default_factory=DataConfig)
    model: ModelConfig = field(default_factory=ModelConfig)
    tts: TtsConfig = field(default_factory=TtsConfig)
    audio: AudioConfig = field(default_factory=AudioConfig)
    parse: ParseConfig = field(default_factory=ParseConfig)
    agent: AgentConfig = field(default_factory=AgentConfig)
    serving: ServingConfig = field(default_factory=ServingConfig)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


_SECTIONS = {"data": DataConfig, "model": ModelConfig, "tts": TtsConfig,
             "audio": AudioConfig, "parse": ParseConfig, "agent": AgentConfig,
             "serving": ServingConfig}


def _build(cls, raw: Optional[Dict[str, Any]]):
    raw = raw or {}
    known = {f.name for f in cls.__dataclass_fields__.values()}  # type: ignore[attr-defined]
    return cls(**{k: v for k, v in raw.items() if k in known})


def load_config(path: Optional[str | os.PathLike] = None) -> AppConfig:
    raw: Dict[str, Any] = {}
    if path is not None:
        p = Path(path)
        if not p.exists():
            raise FileNotFoundError(f"Config not found: {p}")
        raw = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    top = {k: raw[k] for k in ("project_title", "author", "student_id") if k in raw}
    sections = {name: _build(cls, raw.get(name)) for name, cls in _SECTIONS.items()}
    return AppConfig(**top, **sections)


def save_config(cfg: AppConfig, path: str | os.PathLike) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(yaml.safe_dump(cfg.to_dict(), sort_keys=False, allow_unicode=True), encoding="utf-8")


def ensure_dirs() -> Dict[str, Path]:
    dirs = {"artifacts": artifacts_dir(), "data": data_dir(), "models": model_dir(),
            "runs": run_dir(), "outputs": output_dir()}
    for d in dirs.values():
        d.mkdir(parents=True, exist_ok=True)
    return dirs


__all__ = ["DataConfig", "ModelConfig", "TtsConfig", "AudioConfig", "ParseConfig",
           "AgentConfig", "ServingConfig", "AppConfig", "SEMIOTIC_CLASSES",
           "load_config", "save_config", "ensure_dirs",
           "artifacts_dir", "data_dir", "model_dir", "run_dir", "output_dir"]
